/*
サンプルクエリ、サンプルストアドプロシージャ、サンプルストアドファンクションを動作させるための環境を構築する。
*/

DROP TABLE TBL_EXAMPLE
GO

CREATE TABLE TBL_EXAMPLE
(
    ID int NOT NULL, 
    CAPTION nvarchar(20), 
    CONSTRAINT "pk_EXAMPLE" PRIMARY KEY (ID)
)
GO

DROP TABLE Employee
GO

CREATE TABLE Employee
(
    StaffNum CHAR(5),
    StaffName NVARCHAR(20),
    StaffKind CHAR(1),
    CONSTRAINT "pk_EMP" PRIMARY KEY (StaffNum)
)
GO

DROP TABLE RESULT_TABLE
GO

CREATE TABLE RESULT_TABLE
(
    ID          INT NOT NULL,
    SITUATION   NVARCHAR(10),
    DATEADDED   DATETIME2 DEFAULT SYSDATETIME(),
    UPDATED     DATETIME2,
    CONSTRAINT "pk_RT" PRIMARY KEY (ID)
)
GO

DROP TABLE TBL_SOURCE
GO

CREATE TABLE TBL_SOURCE
(
    ID          INT NOT NULL,
    SITUATION   NVARCHAR(10),
    CONSTRAINT "pk_SRC" PRIMARY KEY (ID)
)
GO

DROP TABLE TBL_SAMPLE_WORK
GO

CREATE TABLE TBL_SAMPLE_WORK
(
    ID int NOT NULL, 
    CAPTION nvarchar(20), 
    CONSTRAINT "pk_SAMPLE_WORK" PRIMARY KEY (ID)
)
GO

DROP TABLE TBL_EXAMPLE2
GO

CREATE TABLE TBL_EXAMPLE2
(
    ID INT NOT NULL,
    CAPTION NVARCHAR(20),
    SCHOOL_YEAR CHAR(1) NOT NULL DEFAULT 1,
    CLASS CHAR(1) NOT NULL DEFAULT 1,
    CONSTRAINT "pk_EXAMPLE2" PRIMARY KEY (ID)
)
GO

DROP TABLE Customer
GO

CREATE TABLE Customer
(
    CUSTOMER_ID INT NOT NULL PRIMARY KEY,
    CUSTOMER_NAME NVARCHAR(20)
)
GO

DROP TABLE Shipping
GO

CREATE TABLE Shipping
(
    SHIPPING_ID INT NOT NULL PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    SHIPPING_NAME NVARCHAR(20)
)
GO

--処理時間計測（目安）
DECLARE @StartTime datetime;
SET @StartTime = GETDATE();

--実行するSQL、ストアドを記述

SELECT CONVERT(varchar, GETDATE() - @StartTime, 114) AS 実行時間;
